network:
  version: 2
  renderer: networkd
  ethernets:
    ens18:
      addresses:
        - 192.168.1.11/24
      nameservers:
        addresses: [192.168.1.14, 1.1.1.1]
      routes:
        - to: default
          via: 192.168.1.1
